import {
  useDrawer,
  useDrawerDispatch,
} from "../../contexts/drawer/drawer.provider";
import { useState, useEffect } from "react";
import { Button } from "react-bootstrap";
import { mvpSmartContractService } from "../../../services/mvp-smart-contract.service";
import { createEvent } from "../../../services/event.service";
import { 
  errorFunction, 
  loadingFunction ,
  succesfullBlockchainCreation
} from "../../toasts/sweetAlerts";

export default function CreateEvent() {
  const {
    poapIssuer,
    ethereum: { provider },
  } = useDrawer();
  const dispatch = useDrawerDispatch();

  // Smart contract required fields only
  const [maxSupply, setMaxSupply] = useState(0);
  const [showEventDates, setShowEventDates] = useState(false);
  
  // Off-chain data fields (required: title, description, imageUrl)
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [eventStartDate, setEventStartDate] = useState("");
  const [eventEndDate, setEventEndDate] = useState("");
  
  // Image preview state
  const [imagePreview, setImagePreview] = useState(null);
  const [imageError, setImageError] = useState(false);
  const [imageLoading, setImageLoading] = useState(false);
  
  // Check if form is valid
  const isFormValid = () => {
    // Always need Maximum Supply > 0, Event Start Date, Title, Description, and Image URL
    // eventId is auto-generated by backend
    return maxSupply > 0 && eventStartDate.trim() && title.trim() && description.trim() && imageUrl.trim();
  };

  // Validate contract requirements
  const validateContractRequirements = () => {
    const errors = [];
    
    // Validate maxSupply > 0
    if (maxSupply <= 0) {
      errors.push("Maximum Supply must be greater than 0");
    }
    
    // Validate eventOrganizer (provider.address)
    if (!provider || !provider.address || provider.address === "0x0000000000000000000000000000000000000000") {
      errors.push("Valid wallet address is required");
    }
    
    // Validate event end date is at least 3 days after start date
    if (eventEndDate && eventEndDate.trim() !== "" && eventStartDate && eventStartDate.trim() !== "") {
      const startDate = new Date(eventStartDate);
      const endDate = new Date(eventEndDate);
      
      // Calculate difference in milliseconds, then convert to days
      const diffTime = endDate.getTime() - startDate.getTime();
      const diffDays = diffTime / (1000 * 60 * 60 * 24);
      
      if (diffDays < 3) {
        errors.push("Event end date must be at least 3 days after the start date (contract requirement)");
      }
    }
    
    return errors;
  };
  const [loading, setLoading] = useState(false);

  // Get today's date in YYYY-MM-DD format for min date validation
  const getTodayDate = () => {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    const day = String(today.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  // Handle image URL change and preview
  useEffect(() => {
    if (imageUrl.trim()) {
      setImageLoading(true);
      setImageError(false);
      const img = new Image();
      img.onload = () => {
        setImagePreview(imageUrl);
        setImageLoading(false);
        setImageError(false);
      };
      img.onerror = () => {
        setImagePreview(null);
        setImageLoading(false);
        setImageError(true);
      };
      img.src = imageUrl;
    } else {
      setImagePreview(null);
      setImageError(false);
      setImageLoading(false);
    }
  }, [imageUrl]);

  const toggleEventDates = () => {
    setShowEventDates(!showEventDates);
    // Only clear end date when toggle is turned off (start date is always required)
    if (showEventDates) {
      setEventEndDate("");
    }
  };

  // Validate and clear end date if it's invalid when start date changes
  useEffect(() => {
    if (showEventDates && eventEndDate && eventStartDate) {
      const startDate = new Date(eventStartDate);
      const endDate = new Date(eventEndDate);
      
      // Calculate difference in days
      const diffTime = endDate.getTime() - startDate.getTime();
      const diffDays = diffTime / (1000 * 60 * 60 * 24);
      
      // If end date is before or equal to start date, or less than 3 days after, clear it
      if (endDate <= startDate || diffDays < 3) {
        setEventEndDate("");
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [eventStartDate, showEventDates]); // Only check when start date or toggle changes

  const closeDrawer = () => {
    dispatch({
      type: "CLOSE_DRAWER",
    });
  };

  // const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Validate required fields
    if (!isFormValid()) {
      errorFunction(
        "Validation Error",
        "Please fill in all required fields: Maximum Supply (must be > 0), Event Start Date, Title, Description, and Image URL.",
        ""
      );
      return;
    }
    
    // Validate contract requirements
    const contractErrors = validateContractRequirements();
    if (contractErrors.length > 0) {
      errorFunction(
        "Contract Validation Error",
        contractErrors.join("\n"),
        ""
      );
      return;
    }
    
    setLoading(true);

    try {
      // eventStartDate is now required, so no need to default to today
      const finalEventStartDate = eventStartDate;

      // Calculate mintExpiration from eventEndDate
      let timestamp = 0;
      if (eventEndDate && eventEndDate.trim() !== "") {
        // Convert date to timestamp (in seconds)
        // eventEndDate is in YYYY-MM-DD format
        const endDate = new Date(eventEndDate);
        // Set to end of day to allow minting throughout the event end date
        endDate.setHours(23, 59, 59, 999);
        timestamp = Math.floor(endDate.getTime() / 1000);
      }

      console.log("✅ Timestamp:", timestamp);
      console.log("✅ Event End Date:", eventEndDate);
      console.log("✅ Event Start Date:", finalEventStartDate);

      // STEP 1: Store both offchain and onchain data in backend FIRST
      // Convert date format to ISO string
      // date input returns "YYYY-MM-DD" which needs to be converted to ISO
      const convertToISO = (dateString) => {
        if (!dateString || dateString.trim() === "") return null;
        // dateString is in YYYY-MM-DD format, convert to ISO with timezone
        const date = new Date(dateString);
        return isNaN(date.getTime()) ? null : date.toISOString();
      };

      let startTimeStamp = 0;
      if (finalEventStartDate && finalEventStartDate.trim() !== "") {
        const startDate = new Date(finalEventStartDate);
        // Set to start of day (00:00:00.000) for consistency
        startDate.setHours(0, 0, 0, 0);
        startTimeStamp = Math.floor(startDate.getTime() / 1000);
      }
      console.log("✅ Start Time Stamp:", startTimeStamp);

      // Build event data object with both onchain and offchain data
      // Note: eventId is NOT included - backend will auto-generate it
      const eventData = {
        issuerId: parseInt(poapIssuer.issuerId),
        // eventId is omitted - backend will auto-generate it
        eventMaxSupply: parseInt(maxSupply),
        eventMintExpiration: timestamp,
        eventOrganizer: provider.address,
        title: title.trim(),
        description: description.trim(),
        imageUrl: imageUrl.trim(),
        eventStartDate: startTimeStamp,
        eventEndDate: convertToISO(eventEndDate) || '',
      };

      console.log("✅ Storing event data in backend (offchain + onchain):", eventData);
      loadingFunction("Storing Event Data", "Saving event information...", "");
      
      // Store in backend first - this stores both offchain and onchain data
      // Backend will auto-generate eventId and return it in the response
      const storedEvent = await createEvent(eventData);
      console.log("✅ Event stored in backend:", storedEvent);

      // Check if backend returned an error
      if (!storedEvent || storedEvent.error) {
        throw new Error(storedEvent?.error || storedEvent?.details || "Failed to store event data in backend");
      }

      // Extract the auto-generated eventId from the backend response
      const generatedEventId = storedEvent.eventId;
      if (!generatedEventId) {
        throw new Error("Backend did not return an eventId. Event creation may have failed.");
      }
      console.log("✅ Generated eventId from backend:", generatedEventId);

      // STEP 2: Generate blockchain transaction using the generated eventId
      console.log("✅ Generating blockchain transaction with eventId:", generatedEventId);
      loadingFunction("Preparing Transaction", "Please confirm the transaction in your wallet...", "");
      
      // Generate and send transaction to blockchain with the generated eventId
      const result = await mvpSmartContractService.createEvent(
        parseInt(poapIssuer.issuerId),
        generatedEventId, // Use the auto-generated eventId from backend
        parseInt(maxSupply),
        startTimeStamp,
        timestamp,
        provider.address
      );

      if (result.success) {
        const explorerUrl = `${process.env.REACT_APP_POLYGON_AMOY_BLOCK_EXPLORER_URL}/tx/${result.txHash}`;
        
        // STEP 3: Indexer will automatically update the event with tx hash and block number
        // The indexer (blockchainSync.service.ts) detects the blockchain event
        // and updates the existing database record with transaction_hash and block_number
        // No manual update needed here - the indexer handles it automatically
        
        console.log("✅ Blockchain transaction successful. Indexer will update event metadata automatically.");
        
        closeDrawer();
        succesfullBlockchainCreation(
          "Event Created Successfully",
          `Transaction: ${result.txHash}`,
          explorerUrl
        );
      } else {
        throw new Error("Blockchain transaction failed");
      }
      
    } catch (error) {
      console.error("Error creating event:", error);
      
      // Check for rate limit errors
      const isRateLimit = 
        error.name === "RateLimitError" ||
        error.message?.includes("rate limit") ||
        error.message?.includes("Rate limit") ||
        error.code === -32005 ||
        error.data?.httpStatus === 429;
      
      if (isRateLimit) {
        errorFunction(
          "Rate Limit Error",
          "The network is currently busy. Please wait a few seconds and try again.",
          ""
        );
      } else {
        errorFunction(
          "Error",
          error.message || "An error occurred while creating the event. Please try again.",
          ""
        );
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container absolute top-0 start-0 w-100 h-100 p-3 overflow-auto">
      <div className="drawer-header">
        <div className="d-flex justify-content-start">
          <button
            className="btn btn-close align-content-center px-1 mt-2 position-absolute"
            onClick={closeDrawer}
            aria-label="close"
          ></button>
          <h4 className="align-content-center text-center w-100 m-0 py-3 font-weight-semibold">
            Create POAP EVENT
          </h4>
        </div>
      </div>
      <div className="drawer-body">
        <form className="row g-3" onSubmit={handleSubmit}>
          {/* Basic Information Section */}
          <div className="col-12 mb-3">
            <h6 className="mb-3 text-primary font-weight-semibold">Basic Information</h6>
            <small className="form-text text-muted">
              Event ID will be automatically generated when you create the event.
            </small>
          </div>

          <div className="col-12">
            <label className="form-label">
              Maximum Supply <span className="text-danger">*</span>
            </label>
            <input
              type="number"
              className={`form-control ${(!maxSupply || maxSupply <= 0) && !isFormValid() ? 'border-warning' : ''}`}
              placeholder="Maximum number of POAPs to mint"
              name="maxSupply"
              value={maxSupply || ''}
              onChange={(event) => {
                const value = Number.parseInt(event.target.value) || 0;
                setMaxSupply(value);
              }}
              required
              min="1"
            />
            <small className="form-text text-muted">
              Maximum number of POAPs that can be minted for this event (must be greater than 0)
            </small>
            {maxSupply <= 0 && maxSupply !== '' && (
              <small className="form-text text-danger d-block mt-1">
                <i className="icofont-warning"></i> Maximum Supply must be greater than 0
              </small>
            )}
          </div>

          {/* Event Dates Section */}
          <div className="col-12">
            <hr className="my-4" style={{ borderColor: '#f1f1f1' }} />
          </div>
          
          <div className="col-12 mb-3">
            <h6 className="mb-3 text-primary font-weight-semibold">Event Dates</h6>
          </div>

          {/* Event Start Date - Always visible and required */}
          <div className="col-12">
            <label className="form-label">
              Event Start Date <span className="text-danger">*</span>
            </label>
            <input
              type="date"
              className={`form-control ${!eventStartDate.trim() && !isFormValid() ? 'border-warning' : ''}`}
              name="eventStartDate"
              value={eventStartDate}
              onChange={(event) => setEventStartDate(event.target.value)}
              min={getTodayDate()}
              required
            />
            <small className="form-text text-muted">
              When the actual event starts.
            </small>
          </div>

          {/* Event End Date - Optional, behind toggle */}
          <div className="col-12 mb-2">
            <div className="d-flex align-items-center justify-content-between">
              <div className="flex-grow-1">
                <h6 className="mb-1 text-primary font-weight-semibold">Event End Date</h6>
                <small className="form-text text-muted d-block">
                  Optional: Set an end date for your event
                </small>
              </div>
              <div className="form-check form-switch ms-3">
                <input
                  className="form-check-input"
                  type="checkbox"
                  id="eventDatesToggle"
                  checked={showEventDates}
                  onChange={toggleEventDates}
                  style={{ cursor: 'pointer' }}
                />
              </div>
            </div>
          </div>

          {showEventDates && (
            <div className="col-12" style={{ animation: 'fadeIn 0.3s ease-in' }}>
              <div className="row g-3">
                <div className="col-12">
                  <label className="form-label">Event End Date</label>
                  <input
                    type="date"
                    className="form-control"
                    name="eventEndDate"
                    value={eventEndDate}
                    onChange={(event) => {
                      const selectedDate = event.target.value;
                      // Validate that selected date is at least 3 days after start date
                      if (eventStartDate && selectedDate) {
                        const startDate = new Date(eventStartDate);
                        const endDate = new Date(selectedDate);
                        const diffTime = endDate.getTime() - startDate.getTime();
                        const diffDays = diffTime / (1000 * 60 * 60 * 24);
                        
                        if (endDate <= startDate || diffDays < 3) {
                          // Don't allow setting end date before/equal to start date or less than 3 days after
                          return;
                        }
                      }
                      setEventEndDate(selectedDate);
                    }}
                    min={eventStartDate ? (() => {
                      // Set min to 3 days after start date (contract requirement)
                      const startDate = new Date(eventStartDate);
                      startDate.setDate(startDate.getDate() + 3);
                      const year = startDate.getFullYear();
                      const month = String(startDate.getMonth() + 1).padStart(2, '0');
                      const day = String(startDate.getDate()).padStart(2, '0');
                      return `${year}-${month}-${day}`;
                    })() : getTodayDate()}
                    disabled={!eventStartDate}
                  />
                  <small className="form-text text-muted">
                    When the actual event ends. Mint expiration will be automatically calculated from this date. Must be at least 3 days after the event start date (contract requirement).
                  </small>
                  {!eventStartDate && (
                    <small className="form-text text-danger d-block mt-1">
                      Please select an event start date first.
                    </small>
                  )}
                  {eventEndDate && eventStartDate && (() => {
                    const startDate = new Date(eventStartDate);
                    const endDate = new Date(eventEndDate);
                    const diffTime = endDate.getTime() - startDate.getTime();
                    const diffDays = diffTime / (1000 * 60 * 60 * 24);
                    
                    if (diffDays < 3) {
                      return (
                        <small className="form-text text-danger d-block mt-1">
                          <i className="icofont-warning"></i> Event end date must be at least 3 days after the start date to meet contract requirements.
                        </small>
                      );
                    }
                    return null;
                  })()}
                </div>
              </div>
            </div>
          )}

          {/* Event Details Section */}
          <div className="col-12">
            <hr className="my-4" style={{ borderColor: '#f1f1f1' }} />
          </div>

          <div className="col-12 mb-3">
            <h6 className="mb-1 text-primary font-weight-semibold">
              Event Details <span className="text-danger">*</span>
            </h6>
            <small className="form-text text-muted">
              Provide information about your event. These details are stored off-chain and help users understand what the event is about.
            </small>
          </div>

          <div className="col-12">
            <label className="form-label">
              Event Title <span className="text-danger">*</span>
            </label>
            <input
              type="text"
              className={`form-control ${!title.trim() && !isFormValid() ? 'border-warning' : ''}`}
              placeholder="e.g., Web3 Conference 2024"
              name="title"
              value={title}
              onChange={(event) => setTitle(event.target.value)}
              required
              maxLength={255}
            />
            <div className="d-flex justify-content-between">
              <small className="form-text text-muted">
                A descriptive title for your event
              </small>
              <small className="form-text text-muted">
                {title.length}/255
              </small>
            </div>
          </div>

          <div className="col-12">
            <label className="form-label">
              Description <span className="text-danger">*</span>
            </label>
            <textarea
              className={`form-control ${!description.trim() && !isFormValid() ? 'border-warning' : ''}`}
              rows="4"
              placeholder="Describe your event, what attendees can expect, etc."
              name="description"
              value={description}
              onChange={(event) => setDescription(event.target.value)}
              required
              maxLength={1000}
              style={{ resize: 'vertical', minHeight: '100px', paddingTop: '10px'}}
            />
            <div className="d-flex justify-content-between">
              <small className="form-text text-muted">
                Detailed description of the event
              </small>
              <small className="form-text text-muted">
                {description.length}/1000
              </small>
            </div>
          </div>

          <div className="col-12">
            <label className="form-label">
              Image URL <span className="text-danger">*</span>
            </label>
            <input
              type="url"
              className={`form-control ${!imageUrl.trim() && !isFormValid() ? 'border-warning' : imageError ? 'border-danger' : ''}`}
              placeholder="https://example.com/event-image.jpg"
              name="imageUrl"
              value={imageUrl}
              onChange={(event) => setImageUrl(event.target.value)}
              required
            />
            <small className="form-text text-muted">
              URL to an image representing your event (banner, logo, etc.)
            </small>
            
            {/* Image Preview */}
            {imageUrl.trim() && (
              <div className="mt-3">
                {imageLoading && (
                  <div className="d-flex align-items-center justify-content-center p-4 border rounded" style={{ minHeight: '150px', backgroundColor: '#f8f9fa' }}>
                    <div className="spinner-border text-primary" role="status">
                      <span className="visually-hidden">Loading...</span>
                    </div>
                  </div>
                )}
                {imageError && (
                  <div className="alert alert-danger py-2 mb-0" role="alert">
                    <small>
                      <i className="icofont-warning"></i> Unable to load image. Please check the URL.
                    </small>
                  </div>
                )}
                {imagePreview && !imageLoading && !imageError && (
                  <div className="border rounded overflow-hidden" style={{ maxHeight: '200px' }}>
                    <img
                      src={imagePreview}
                      alt="Event preview"
                      className="img-fluid w-100"
                      style={{ objectFit: 'cover', maxHeight: '200px' }}
                      onError={() => setImageError(true)}
                    />
                  </div>
                )}
              </div>
            )}
          </div>

        </form>
        {!isFormValid() && (
          <div className="alert alert-warning mb-2 py-2" role="alert" style={{ fontSize: '0.875rem', margin: '8px 0' }}>
            <div className="d-flex align-items-start">
              <i className="icofont-warning me-2 mt-1 flex-shrink-0"></i>
              <div className="flex-grow-1">
                <strong className="d-block mb-1">Please complete all required fields:</strong>
                <div className="d-flex flex-wrap gap-2">
                  {(!maxSupply || maxSupply <= 0) && <span className="badge bg-warning text-dark">Maximum Supply (&gt; 0)</span>}
                  {!eventStartDate.trim() && <span className="badge bg-warning text-dark">Event Start Date</span>}
                  {!title.trim() && <span className="badge bg-warning text-dark">Event Title</span>}
                  {!description.trim() && <span className="badge bg-warning text-dark">Description</span>}
                  {!imageUrl.trim() && <span className="badge bg-warning text-dark">Image URL</span>}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
      <div className="drawer-footer">
        <Button
          type="submit"
          className="btn btn-gradient btn-block w-100"
          onClick={handleSubmit}
          disabled={loading || !isFormValid()}
          style={{ 
            minHeight: '45px',
            fontWeight: '500',
            transition: 'all 0.3s ease'
          }}
        >
          {loading ? (
            <>
              <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
              Creating Event...
            </>
          ) : (
            'Create Event'
          )}
        </Button>
      </div>
    </div>
  );
}
